# This is a basic workflow to help you get started with Actions

name: deploy-auth

# Controls when the workflow will run
on:
  push:
    branches: [main]
    paths:
      - 'auth/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build auth docker image
        run: cd auth && docker build -t yantolee3528/ticketing-auth .
      - name: Login to docker hub
        with:
          username: ${ { secrets.DOCKER_USERNAME } }
          password: ${ { secrets.DOCKER_PASSWORD } }
        uses: docker/login-action@v1
      - name: Push image to docker hub
        run: docker push yantolee3528/ticketing-auth
